Update getting_started.md avoid error from line 338
When the command ScientificTypes.schema
is called in line 338 produce an error message
ERROR: UndefVarError: `ScientificTypes` not defined.

My guess is the command should be:
schema(X)